name = "dailycat"
main = "src/index.js"
compatibility_date = "2025-01-10"
workers_dev = false
kv_namespaces = [ { binding = "meow", id = "56eca4985cda4828a869500462e3295a", preview_id = "56eca4985cda4828a869500462e3295a" } ]

[triggers]
crons = [ "1 5 * * *" ]

[env.dev]
compatibility_date = "2025-01-10"
kv_namespaces = [ { binding = "meow", id = "56eca4985cda4828a869500462e3295a", preview_id = "56eca4985cda4828a869500462e3295a" } ]

[env.dev.triggers]
crons = []
